# 
# Build on ARM64 only
#
language: cpp

arch:
  - arm64

compiler:
  - gcc
  - clang

install: skip

script:
  - sh ./scripts/bootstrap-arm64-travis.sh
  - cd build-aarch64
  - cmake --build .
  - ./verify
