# 
# Build on ARM64 only
#
language: cpp

arch:
  - arm64

compiler:
  - gcc
  - clang


before_install:
  - sudo apt-get -y install ninja-build
addons:
  apt:
    update: true

install: skip

script:
  - sh ./scripts/bootstrap-arm64-travis.sh
  - cd build-aarch64
  - cmake --build .
  - ./verify
