# 
# Build on ARM64 only
#
language: cpp

# Use ubuntu 20.04
dist: focal

arch:
  - arm64

compiler:
  - gcc
  - clang

# envs are used in ./scripts/bootstrap-arm64-travis.sh
env:
  - ENV_MAX_ISA=SSE2 ENV_RAY_PACKETS=Off
  - ENV_MAX_ISA=SSE2 ENV_RAY_PACKETS=On
  - ENV_MAX_ISA=AVX2 ENV_RAY_PACKETS=Off ENV_NEON_AVX2_EMULATION=On
  - ENV_MAX_ISA=AVX2 ENV_RAY_PACKETS=On ENV_NEON_AVX2_EMULATION=On


before_install:
  - sudo apt-get -y install ninja-build
addons:
  apt:
    update: true

install: skip

# limit the number of build jobs(--parallel) trying to avoid build timeout for AVX2 target.
script:
  - cat /proc/meminfo
  - cat /proc/cpuinfo
  - /bin/bash ./scripts/bootstrap-arm64-travis.sh
  - cd build-aarch64
  - cmake --build . --parallel 4
  - ./verify
  - cd ../test/curve
  - make EXTRA_CXXFLAGS="-fsanitize=address" EXTRA_LDFLAGS="-fsanitize=address" EMBREE_LIB_PATH=../../build-aarch64
  - ./run.sh ../../build-aarch64 > /dev/null

